name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity minimal

    - name: Pack
      run: dotnet pack --configuration Release --no-build --version-suffix alpha.$GITHUB_RUN_NUMBER --output nupkgs

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nupkgs
        path: nupkgs

  publish:
    name: Publish
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: nupkgs
        path: nupkgs

    - name: Push
      run: dotnet nuget push "nupkgs/*.nupkg" --source https://nuget.pkg.github.com/teraa/index.json --api-key $GITHUB_TOKEN --skip-duplicate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

env:
  DOTNET_NOLOGO : true
  DOTNET_CLI_TELEMETRY_OPTOUT : true
  EVENT_NAME : ${{ github.event_name }}
